# Generated by Django 2.0.4 on 2018-04-25 19:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=1000, verbose_name='Address')),
                ('zip_code', models.CharField(max_length=12, verbose_name='ZIP/ Postal Code')),
                ('city', models.CharField(max_length=1000, verbose_name='City')),
                ('state', models.CharField(max_length=100, verbose_name='State')),
                ('country', models.CharField(max_length=1000, verbose_name='Country')),
                ('email', models.EmailField(blank=True, max_length=70, null=True, unique=True)),
                ('phone', models.CharField(max_length=12)),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('url', models.URLField(unique=True, verbose_name='URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
